POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "organizationName": "OpsFlow Demo",
    "name": "Danilo Macedo",
    "email": "danilo@opsflow.test",
    "password": "SecurePassword123!"
}